from decimal import Decimal

from django.core.management.base import BaseCommand
from django.utils import timezone

from dealer_ai.models import Vehicle


DEMO_SOURCE = "demo_seed"


DEMO_VEHICLES = [
    {
        "stock_number": "FF-2025-001",
        "year": 2025,
        "model": "F-150",
        "trim": "XLT SuperCrew 4x4",
        "body_style": "truck",
        "condition": "new",
        "mileage": 8,
        "price": Decimal("62995.00"),
        "msrp": Decimal("64500.00"),
        "exterior_color": "Oxford White",
        "interior_color": "Medium Dark Slate",
        "drivetrain": "4x4",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.7L EcoBoost V6",
        "features": ["Tow Package", "FordPass Connect", "Sync 4", "Heated Seats"],
        "description": "Brand-new F-150 XLT with the popular 2.7L EcoBoost, tow package, and Sync 4. Built for Oklahoma work-and-weekend hauling.",
        "image_url": "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800",
    },
    {
        "stock_number": "FF-2025-002",
        "year": 2025,
        "model": "F-150",
        "trim": "Lariat SuperCrew 4x4",
        "body_style": "truck",
        "condition": "new",
        "mileage": 5,
        "price": Decimal("78495.00"),
        "msrp": Decimal("80200.00"),
        "exterior_color": "Antimatter Blue",
        "interior_color": "Black Leather",
        "drivetrain": "4x4",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "3.5L EcoBoost V6",
        "features": ["Leather", "Pano Roof", "B&O Audio", "BlueCruise", "Tow Tech"],
        "description": "Lariat with the 3.5L EcoBoost — heated and cooled leather, panoramic roof, BlueCruise hands-free highway driving.",
        "image_url": "https://images.unsplash.com/photo-1571603375944-ed4f5b6f2632?w=800",
    },
    {
        "stock_number": "FF-2025-003",
        "year": 2025,
        "model": "Ranger",
        "trim": "XLT SuperCrew 4x4",
        "body_style": "truck",
        "condition": "new",
        "mileage": 9,
        "price": Decimal("47995.00"),
        "msrp": Decimal("48900.00"),
        "exterior_color": "Shadow Black",
        "interior_color": "Ebony Cloth",
        "drivetrain": "4x4",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.3L EcoBoost I-4",
        "features": ["Tow Package", "Sync 4", "Trail Control"],
        "description": "Right-sized midsize pickup. Easier to park than the F-150 with plenty of capability for weekend trips.",
        "image_url": "https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800",
    },
    {
        "stock_number": "FF-2025-004",
        "year": 2025,
        "model": "Maverick",
        "trim": "XLT Hybrid SuperCrew",
        "body_style": "truck",
        "condition": "new",
        "mileage": 12,
        "price": Decimal("33495.00"),
        "msrp": Decimal("34200.00"),
        "exterior_color": "Velocity Blue",
        "interior_color": "Black Cloth",
        "drivetrain": "FWD",
        "transmission": "eCVT",
        "fuel_type": "Hybrid",
        "engine": "2.5L iVCT Atkinson Hybrid",
        "features": ["Hybrid", "FlexBed", "Sync 4", "FordPass"],
        "description": "Compact hybrid pickup that gets ~42 mpg city. Great for first-time truck buyers and commuters.",
        "image_url": "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=800",
    },
    {
        "stock_number": "FF-2025-005",
        "year": 2025,
        "model": "Bronco",
        "trim": "Outer Banks 4-Door",
        "body_style": "suv",
        "condition": "new",
        "mileage": 11,
        "price": Decimal("64995.00"),
        "msrp": Decimal("66400.00"),
        "exterior_color": "Cactus Gray",
        "interior_color": "Roast Leather",
        "drivetrain": "4x4",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.7L EcoBoost V6",
        "features": ["Removable Top", "Sasquatch Tires", "Leather", "Trail Toolbox"],
        "description": "Outer Banks 4-door Bronco with the 2.7L V6 and removable top. Built for back roads, ranches, and weekend trails.",
        "image_url": "https://images.unsplash.com/photo-1632245889029-e406faaa34cd?w=800",
    },
    {
        "stock_number": "FF-2025-006",
        "year": 2025,
        "model": "Bronco Sport",
        "trim": "Big Bend AWD",
        "body_style": "suv",
        "condition": "new",
        "mileage": 14,
        "price": Decimal("38995.00"),
        "msrp": Decimal("39800.00"),
        "exterior_color": "Area 51",
        "interior_color": "Ebony Cloth",
        "drivetrain": "AWD",
        "transmission": "8-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "1.5L EcoBoost I-3",
        "features": ["AWD", "Heated Seats", "Sync 3", "Trail Modes"],
        "description": "City-friendly compact SUV with off-road styling and AWD — a smart all-weather everyday driver.",
        "image_url": "https://images.unsplash.com/photo-1629293363663-a7e8e9846a83?w=800",
    },
    {
        "stock_number": "FF-2025-007",
        "year": 2025,
        "model": "Explorer",
        "trim": "ST-Line AWD",
        "body_style": "suv",
        "condition": "new",
        "mileage": 7,
        "price": Decimal("63995.00"),
        "msrp": Decimal("65500.00"),
        "exterior_color": "Star White",
        "interior_color": "Black ActiveX",
        "drivetrain": "AWD",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.3L EcoBoost I-4",
        "features": ["3rd Row", "BlueCruise", "Pano Roof", "B&O Audio"],
        "description": "Three-row family SUV with sportier ST-Line styling. BlueCruise makes long highway runs a breeze.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
    {
        "stock_number": "FF-2025-008",
        "year": 2025,
        "model": "Escape",
        "trim": "ST-Line AWD",
        "body_style": "suv",
        "condition": "new",
        "mileage": 9,
        "price": Decimal("39995.00"),
        "msrp": Decimal("41200.00"),
        "exterior_color": "Iconic Silver",
        "interior_color": "Ebony",
        "drivetrain": "AWD",
        "transmission": "8-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.0L EcoBoost I-4",
        "features": ["AWD", "Heated Seats", "Sync 4", "Adaptive Cruise"],
        "description": "Compact AWD SUV that splits the difference between fuel economy and capability.",
        "image_url": "https://images.unsplash.com/photo-1591293836027-e05b48473b67?w=800",
    },
    {
        "stock_number": "FF-2025-009",
        "year": 2025,
        "model": "Mustang Mach-E",
        "trim": "Premium AWD Extended Range",
        "body_style": "ev",
        "condition": "new",
        "mileage": 6,
        "price": Decimal("64995.00"),
        "msrp": Decimal("66500.00"),
        "exterior_color": "Rapid Red",
        "interior_color": "Black ActiveX",
        "drivetrain": "AWD",
        "transmission": "Single-Speed EV",
        "fuel_type": "Electric",
        "engine": "Dual-Motor AWD, 91 kWh",
        "features": ["AWD EV", "BlueCruise", "Pano Roof", "B&O Audio", "DC Fast Charge"],
        "description": "All-electric Mustang Mach-E Premium with extended-range battery (~290 mile range) and AWD.",
        "image_url": "https://images.unsplash.com/photo-1633509817627-f5fadccd5045?w=800",
    },
    {
        "stock_number": "FF-2024-010",
        "year": 2024,
        "model": "Mustang",
        "trim": "GT Premium Coupe",
        "body_style": "car",
        "condition": "new",
        "mileage": 16,
        "price": Decimal("58995.00"),
        "msrp": Decimal("60800.00"),
        "exterior_color": "Grabber Blue",
        "interior_color": "Black Leather",
        "drivetrain": "RWD",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "5.0L Coyote V8",
        "features": ["V8", "Performance Pack", "Brembo Brakes", "Active Exhaust"],
        "description": "Last-of-the-V8 Mustang GT — Coyote V8, 10-speed auto, active exhaust. End of an era.",
        "image_url": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800",
    },
    # Used / certified pre-owned
    {
        "stock_number": "FF-USED-101",
        "year": 2022,
        "model": "F-150",
        "trim": "XLT SuperCrew 4x4",
        "body_style": "truck",
        "condition": "certified",
        "mileage": 30000,
        "price": Decimal("48995.00"),
        "exterior_color": "Magnetic Gray",
        "interior_color": "Medium Dark Slate",
        "drivetrain": "4x4",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "5.0L Ti-VCT V8",
        "features": ["Tow Package", "Sync 4", "Heated Seats", "CPO Warranty"],
        "description": "Certified Pre-Owned F-150 XLT with the 5.0L V8. One owner, clean Carfax, included Ford CPO coverage.",
        "image_url": "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800",
    },
    {
        "stock_number": "FF-USED-102",
        "year": 2021,
        "model": "Escape",
        "trim": "Titanium Hybrid AWD",
        "body_style": "suv",
        "condition": "used",
        "mileage": 45000,
        "price": Decimal("28995.00"),
        "exterior_color": "Star White",
        "interior_color": "Sandstone Leather",
        "drivetrain": "AWD",
        "transmission": "eCVT",
        "fuel_type": "Hybrid",
        "engine": "2.5L iVCT Atkinson Hybrid",
        "features": ["Hybrid", "AWD", "Leather", "Pano Roof"],
        "description": "Hybrid Escape Titanium AWD — fuel-efficient family SUV with leather and panoramic roof.",
        "image_url": "https://images.unsplash.com/photo-1591293836027-e05b48473b67?w=800",
    },
    {
        "stock_number": "FF-USED-103",
        "year": 2020,
        "model": "Explorer",
        "trim": "Limited 4WD",
        "body_style": "suv",
        "condition": "used",
        "mileage": 57000,
        "price": Decimal("36995.00"),
        "exterior_color": "Agate Black",
        "interior_color": "Ebony Leather",
        "drivetrain": "4x4",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.3L EcoBoost I-4",
        "features": ["3rd Row", "Leather", "Pano Roof", "Tow Package"],
        "description": "Limited Explorer with the EcoBoost — three rows, leather, and tow package. Family-ready.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
    {
        "stock_number": "FF-USED-104",
        "year": 2019,
        "model": "Ranger",
        "trim": "XLT SuperCrew 4x4",
        "body_style": "truck",
        "condition": "used",
        "mileage": 73500,
        "price": Decimal("26995.00"),
        "exterior_color": "Lightning Blue",
        "interior_color": "Ebony Cloth",
        "drivetrain": "4x4",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.3L EcoBoost I-4",
        "features": ["Tow Package", "FX4 Off-Road", "Sync 3"],
        "description": "First-gen reborn Ranger with FX4 package — affordable midsize truck for hunting and camping.",
        "image_url": "https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800",
    },
    {
        "stock_number": "FF-USED-105",
        "year": 2022,
        "model": "Bronco Sport",
        "trim": "Outer Banks AWD",
        "body_style": "suv",
        "condition": "certified",
        "mileage": 26000,
        "price": Decimal("36995.00"),
        "exterior_color": "Cactus Gray",
        "interior_color": "Navy Pier Leather",
        "drivetrain": "AWD",
        "transmission": "8-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.0L EcoBoost I-4",
        "features": ["AWD", "Leather", "Heated Seats", "CPO Warranty"],
        "description": "Certified Bronco Sport Outer Banks with leather and the 2.0L EcoBoost.",
        "image_url": "https://images.unsplash.com/photo-1629293363663-a7e8e9846a83?w=800",
    },
    {
        "stock_number": "FF-USED-106",
        "year": 2021,
        "model": "Mustang Mach-E",
        "trim": "Select RWD",
        "body_style": "ev",
        "condition": "used",
        "mileage": 35000,
        "price": Decimal("38995.00"),
        "exterior_color": "Shadow Black",
        "interior_color": "Black ActiveX",
        "drivetrain": "RWD",
        "transmission": "Single-Speed EV",
        "fuel_type": "Electric",
        "engine": "Single-Motor RWD, 70 kWh",
        "features": ["EV", "Heated Seats", "Sync 4A", "DC Fast Charge"],
        "description": "Entry-level Mach-E Select RWD — affordable used EV with ~230 mile range.",
        "image_url": "https://images.unsplash.com/photo-1633509817627-f5fadccd5045?w=800",
    },
    # ---- Under $15k budget band (older used, ~$300/mo target) ------------
    {
        "stock_number": "FF-USED-201",
        "year": 2014,
        "make": "Ford",
        "model": "Fusion",
        "trim": "SE",
        "body_style": "car",
        "condition": "used",
        "mileage": 105000,
        "price": Decimal("11995.00"),
        "exterior_color": "Ingot Silver",
        "interior_color": "Charcoal Cloth",
        "drivetrain": "FWD",
        "transmission": "6-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.5L iVCT I-4",
        "features": ["Sync", "Backup Camera"],
        "description": "Affordable used Fusion sedan — low monthly payment commuter.",
        "image_url": "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800",
    },
    {
        "stock_number": "FF-USED-202",
        "year": 2015,
        "make": "Toyota",
        "model": "Camry",
        "trim": "LE",
        "body_style": "car",
        "condition": "used",
        "mileage": 95000,
        "price": Decimal("13495.00"),
        "exterior_color": "Super White",
        "interior_color": "Ash Cloth",
        "drivetrain": "FWD",
        "transmission": "6-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.5L I-4",
        "features": ["Bluetooth", "Backup Camera", "Cruise Control"],
        "description": "Reliable trade-in Camry — proven highway commuter.",
        "image_url": "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800",
    },
    {
        "stock_number": "FF-USED-203",
        "year": 2014,
        "make": "Honda",
        "model": "Accord",
        "trim": "LX",
        "body_style": "car",
        "condition": "used",
        "mileage": 110000,
        "price": Decimal("12995.00"),
        "exterior_color": "Modern Steel",
        "interior_color": "Black Cloth",
        "drivetrain": "FWD",
        "transmission": "CVT",
        "fuel_type": "Gasoline",
        "engine": "2.4L I-4",
        "features": ["Bluetooth", "Backup Camera"],
        "description": "Trade-in Accord LX. Honda reliability for an entry-budget shopper.",
        "image_url": "https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?w=800",
    },
    {
        "stock_number": "FF-USED-204",
        "year": 2013,
        "make": "Chevrolet",
        "model": "Malibu",
        "trim": "LT",
        "body_style": "car",
        "condition": "used",
        "mileage": 115000,
        "price": Decimal("10995.00"),
        "exterior_color": "Black Granite",
        "interior_color": "Jet Black Cloth",
        "drivetrain": "FWD",
        "transmission": "6-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.5L Ecotec I-4",
        "features": ["MyLink", "Backup Camera"],
        "description": "Budget-friendly Malibu LT — solid daily driver under $11k.",
        "image_url": "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800",
    },
    {
        "stock_number": "FF-USED-205",
        "year": 2014,
        "make": "Nissan",
        "model": "Altima",
        "trim": "2.5",
        "body_style": "car",
        "condition": "used",
        "mileage": 120000,
        "price": Decimal("9995.00"),
        "exterior_color": "Brilliant Silver",
        "interior_color": "Charcoal Cloth",
        "drivetrain": "FWD",
        "transmission": "CVT",
        "fuel_type": "Gasoline",
        "engine": "2.5L I-4",
        "features": ["Bluetooth", "Cruise Control"],
        "description": "Trade-in Altima 2.5 — under $10k commuter sedan.",
        "image_url": "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800",
    },
    # ---- $15-25k band (~$400/mo target) ----------------------------------
    {
        "stock_number": "FF-USED-301",
        "year": 2018,
        "make": "Ford",
        "model": "Escape",
        "trim": "SE FWD",
        "body_style": "suv",
        "condition": "used",
        "mileage": 78000,
        "price": Decimal("17995.00"),
        "exterior_color": "Magnetic",
        "interior_color": "Charcoal Black",
        "drivetrain": "FWD",
        "transmission": "6-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "1.5L EcoBoost I-4",
        "features": ["Sync 3", "Backup Camera", "Heated Seats"],
        "description": "Used Escape SE — compact SUV at a commuter-friendly price.",
        "image_url": "https://images.unsplash.com/photo-1591293836027-e05b48473b67?w=800",
    },
    {
        "stock_number": "FF-USED-302",
        "year": 2017,
        "make": "Toyota",
        "model": "Camry",
        "trim": "SE",
        "body_style": "car",
        "condition": "used",
        "mileage": 65000,
        "price": Decimal("19995.00"),
        "exterior_color": "Midnight Black",
        "interior_color": "Black Cloth",
        "drivetrain": "FWD",
        "transmission": "6-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.5L I-4",
        "features": ["Bluetooth", "Backup Camera", "Sport Trim"],
        "description": "Camry SE trade-in. Sportier styling, mid-bracket budget.",
        "image_url": "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800",
    },
    {
        "stock_number": "FF-USED-303",
        "year": 2018,
        "make": "Honda",
        "model": "Accord",
        "trim": "Sport",
        "body_style": "car",
        "condition": "used",
        "mileage": 72000,
        "price": Decimal("21495.00"),
        "exterior_color": "Lunar Silver",
        "interior_color": "Black Cloth",
        "drivetrain": "FWD",
        "transmission": "CVT",
        "fuel_type": "Gasoline",
        "engine": "1.5L Turbo I-4",
        "features": ["Bluetooth", "Lane Assist", "Backup Camera"],
        "description": "Accord Sport — sharp styling, modern safety, used budget.",
        "image_url": "https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?w=800",
    },
    {
        "stock_number": "FF-USED-304",
        "year": 2019,
        "make": "Ford",
        "model": "Fusion",
        "trim": "Titanium",
        "body_style": "car",
        "condition": "used",
        "mileage": 55000,
        "price": Decimal("19995.00"),
        "exterior_color": "Oxford White",
        "interior_color": "Ebony Leather",
        "drivetrain": "FWD",
        "transmission": "6-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.0L EcoBoost I-4",
        "features": ["Leather", "Sync 3", "Heated Seats", "Backup Camera"],
        "description": "Fusion Titanium — last-of-the-line Fusion with leather and Sync 3.",
        "image_url": "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800",
    },
    {
        "stock_number": "FF-USED-305",
        "year": 2017,
        "make": "Chevrolet",
        "model": "Equinox",
        "trim": "LT",
        "body_style": "suv",
        "condition": "used",
        "mileage": 88000,
        "price": Decimal("16995.00"),
        "exterior_color": "Summit White",
        "interior_color": "Jet Black Cloth",
        "drivetrain": "FWD",
        "transmission": "6-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.4L Ecotec I-4",
        "features": ["MyLink", "Backup Camera"],
        "description": "Equinox LT trade-in — practical compact SUV.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
    {
        "stock_number": "FF-USED-306",
        "year": 2018,
        "make": "Nissan",
        "model": "Altima",
        "trim": "SR",
        "body_style": "car",
        "condition": "used",
        "mileage": 70000,
        "price": Decimal("17495.00"),
        "exterior_color": "Gun Metallic",
        "interior_color": "Charcoal Cloth",
        "drivetrain": "FWD",
        "transmission": "CVT",
        "fuel_type": "Gasoline",
        "engine": "2.5L I-4",
        "features": ["Backup Camera", "Sport Trim"],
        "description": "Altima SR. Sporty trim at a sedan budget.",
        "image_url": "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800",
    },
    {
        "stock_number": "FF-USED-307",
        "year": 2017,
        "make": "Ford",
        "model": "Mustang",
        "trim": "EcoBoost Coupe",
        "body_style": "car",
        "condition": "used",
        "mileage": 50000,
        "price": Decimal("22995.00"),
        "exterior_color": "Race Red",
        "interior_color": "Ebony Cloth",
        "drivetrain": "RWD",
        "transmission": "6-Speed Manual",
        "fuel_type": "Gasoline",
        "engine": "2.3L EcoBoost I-4",
        "features": ["Manual Transmission", "Sync 3", "Track Apps"],
        "description": "Mustang EcoBoost coupe — fun-to-drive at a used budget.",
        "image_url": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800",
    },
    {
        "stock_number": "FF-USED-308",
        "year": 2016,
        "make": "Honda",
        "model": "CR-V",
        "trim": "EX",
        "body_style": "suv",
        "condition": "used",
        "mileage": 95000,
        "price": Decimal("18495.00"),
        "exterior_color": "Modern Steel",
        "interior_color": "Black Cloth",
        "drivetrain": "AWD",
        "transmission": "CVT",
        "fuel_type": "Gasoline",
        "engine": "2.4L I-4",
        "features": ["Sunroof", "Backup Camera", "Heated Seats"],
        "description": "CR-V EX AWD — practical family SUV with sunroof.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
    # ---- $25-35k band ($500-$650/mo target) ------------------------------
    {
        "stock_number": "FF-USED-401",
        "year": 2021,
        "make": "Ford",
        "model": "Escape",
        "trim": "Titanium FWD",
        "body_style": "suv",
        "condition": "used",
        "mileage": 35000,
        "price": Decimal("26995.00"),
        "exterior_color": "Iconic Silver",
        "interior_color": "Sandstone Leather",
        "drivetrain": "FWD",
        "transmission": "8-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.0L EcoBoost I-4",
        "features": ["Leather", "Sync 4", "Pano Roof", "Heated Seats"],
        "description": "Escape Titanium — upper-trim with leather and pano roof.",
        "image_url": "https://images.unsplash.com/photo-1591293836027-e05b48473b67?w=800",
    },
    {
        "stock_number": "FF-USED-402",
        "year": 2020,
        "make": "Toyota",
        "model": "RAV4",
        "trim": "LE",
        "body_style": "suv",
        "condition": "used",
        "mileage": 45000,
        "price": Decimal("27995.00"),
        "exterior_color": "Magnetic Gray",
        "interior_color": "Black Cloth",
        "drivetrain": "AWD",
        "transmission": "8-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.5L I-4",
        "features": ["AWD", "Backup Camera", "Lane Assist"],
        "description": "RAV4 LE AWD — popular compact SUV trade-in.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
    {
        "stock_number": "FF-USED-403",
        "year": 2021,
        "make": "Chevrolet",
        "model": "Equinox",
        "trim": "LT AWD",
        "body_style": "suv",
        "condition": "used",
        "mileage": 30000,
        "price": Decimal("26495.00"),
        "exterior_color": "Mosaic Black",
        "interior_color": "Jet Black Cloth",
        "drivetrain": "AWD",
        "transmission": "6-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "1.5L Turbo I-4",
        "features": ["AWD", "Heated Seats", "MyLink"],
        "description": "Equinox LT AWD — well-equipped compact SUV trade.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
    {
        "stock_number": "FF-USED-404",
        "year": 2020,
        "make": "Ford",
        "model": "Edge",
        "trim": "SEL AWD",
        "body_style": "suv",
        "condition": "used",
        "mileage": 50000,
        "price": Decimal("27995.00"),
        "exterior_color": "Magnetic",
        "interior_color": "Ebony Leather",
        "drivetrain": "AWD",
        "transmission": "8-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.0L EcoBoost I-4",
        "features": ["Leather", "AWD", "Sync 4", "Adaptive Cruise"],
        "description": "Edge SEL AWD — midsize family SUV with leather.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
    {
        "stock_number": "FF-USED-405",
        "year": 2019,
        "make": "Toyota",
        "model": "Tacoma",
        "trim": "SR Double Cab 4x2",
        "body_style": "truck",
        "condition": "used",
        "mileage": 60000,
        "price": Decimal("28995.00"),
        "exterior_color": "Cement",
        "interior_color": "Cement Cloth",
        "drivetrain": "RWD",
        "transmission": "6-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.7L I-4",
        "features": ["Tow Package", "Backup Camera"],
        "description": "Tacoma SR Double Cab 4x2. Toyota reliability in midsize truck form.",
        "image_url": "https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800",
    },
    {
        "stock_number": "FF-USED-406",
        "year": 2020,
        "make": "Chevrolet",
        "model": "Colorado",
        "trim": "WT 4x2",
        "body_style": "truck",
        "condition": "used",
        "mileage": 55000,
        "price": Decimal("25495.00"),
        "exterior_color": "Summit White",
        "interior_color": "Jet Black Cloth",
        "drivetrain": "RWD",
        "transmission": "6-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.5L I-4",
        "features": ["Tow Package", "Backup Camera"],
        "description": "Colorado WT — work-truck pricing without sacrificing capability.",
        "image_url": "https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800",
    },
    {
        "stock_number": "FF-USED-407",
        "year": 2021,
        "make": "Honda",
        "model": "CR-V",
        "trim": "EX-L AWD",
        "body_style": "suv",
        "condition": "used",
        "mileage": 28000,
        "price": Decimal("29995.00"),
        "exterior_color": "Crystal Black",
        "interior_color": "Gray Leather",
        "drivetrain": "AWD",
        "transmission": "CVT",
        "fuel_type": "Gasoline",
        "engine": "1.5L Turbo I-4",
        "features": ["Leather", "AWD", "Sunroof", "Heated Seats"],
        "description": "CR-V EX-L AWD — well-equipped compact SUV with leather.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
    {
        "stock_number": "FF-USED-408",
        "year": 2019,
        "make": "GMC",
        "model": "Terrain",
        "trim": "SLE AWD",
        "body_style": "suv",
        "condition": "used",
        "mileage": 65000,
        "price": Decimal("24995.00"),
        "exterior_color": "Quicksilver Metallic",
        "interior_color": "Jet Black Cloth",
        "drivetrain": "AWD",
        "transmission": "9-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "1.5L Turbo I-4",
        "features": ["AWD", "Backup Camera", "Heated Seats"],
        "description": "Terrain SLE AWD trade-in — under-$25k compact SUV.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
    {
        "stock_number": "FF-USED-409",
        "year": 2021,
        "make": "Nissan",
        "model": "Frontier",
        "trim": "King Cab S",
        "body_style": "truck",
        "condition": "used",
        "mileage": 40000,
        "price": Decimal("27495.00"),
        "exterior_color": "Glacier White",
        "interior_color": "Charcoal Cloth",
        "drivetrain": "RWD",
        "transmission": "9-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "3.8L V6",
        "features": ["Tow Package", "Backup Camera"],
        "description": "Frontier King Cab — affordable midsize truck trade.",
        "image_url": "https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800",
    },
    {
        "stock_number": "FF-USED-410",
        "year": 2020,
        "make": "Jeep",
        "model": "Grand Cherokee",
        "trim": "Laredo",
        "body_style": "suv",
        "condition": "used",
        "mileage": 58000,
        "price": Decimal("32995.00"),
        "exterior_color": "Bright White",
        "interior_color": "Black Cloth",
        "drivetrain": "4x4",
        "transmission": "8-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "3.6L V6",
        "features": ["4x4", "Tow Package", "Heated Seats"],
        "description": "Grand Cherokee Laredo 4x4 trade — proven all-season SUV.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
    # ---- $35-50k band ($700-$900/mo target stretch) ----------------------
    {
        "stock_number": "FF-USED-501",
        "year": 2022,
        "make": "Ford",
        "model": "F-150",
        "trim": "XLT 2WD",
        "body_style": "truck",
        "condition": "used",
        "mileage": 22000,
        "price": Decimal("38995.00"),
        "exterior_color": "Antimatter Blue",
        "interior_color": "Medium Dark Slate",
        "drivetrain": "RWD",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "3.3L Ti-VCT V6",
        "features": ["Sync 4", "Tow Package", "Backup Camera"],
        "description": "F-150 XLT 2WD — popular fleet-style trim at used pricing.",
        "image_url": "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800",
    },
    {
        "stock_number": "FF-USED-502",
        "year": 2022,
        "make": "Toyota",
        "model": "Tundra",
        "trim": "SR5 4x4",
        "body_style": "truck",
        "condition": "used",
        "mileage": 28000,
        "price": Decimal("44995.00"),
        "exterior_color": "Magnetic Gray",
        "interior_color": "Black Cloth",
        "drivetrain": "4x4",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "3.5L Twin-Turbo V6",
        "features": ["4x4", "Tow Package", "Heated Seats"],
        "description": "Tundra SR5 4x4 — full-size Toyota trade.",
        "image_url": "https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800",
    },
    {
        "stock_number": "FF-USED-503",
        "year": 2023,
        "make": "Ford",
        "model": "Ranger",
        "trim": "Lariat 4x4",
        "body_style": "truck",
        "condition": "certified",
        "mileage": 18000,
        "price": Decimal("39995.00"),
        "exterior_color": "Velocity Blue",
        "interior_color": "Ebony Leather",
        "drivetrain": "4x4",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.3L EcoBoost I-4",
        "features": ["Leather", "4x4", "Sync 4", "Tow Package", "CPO Warranty"],
        "description": "Ranger Lariat 4x4 CPO — leather and Sync 4 with Ford warranty.",
        "image_url": "https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800",
    },
    {
        "stock_number": "FF-USED-504",
        "year": 2022,
        "make": "Chevrolet",
        "model": "Silverado 1500",
        "trim": "RST 4x4",
        "body_style": "truck",
        "condition": "used",
        "mileage": 25000,
        "price": Decimal("42995.00"),
        "exterior_color": "Black",
        "interior_color": "Jet Black Leather",
        "drivetrain": "4x4",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "5.3L V8",
        "features": ["4x4", "Leather", "Tow Package", "MyLink"],
        "description": "Silverado 1500 RST 4x4 — full-size truck with the 5.3L V8.",
        "image_url": "https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800",
    },
    {
        "stock_number": "FF-USED-505",
        "year": 2021,
        "make": "Ram",
        "model": "1500",
        "trim": "Big Horn 4x4",
        "body_style": "truck",
        "condition": "used",
        "mileage": 32000,
        "price": Decimal("39995.00"),
        "exterior_color": "Diamond Black",
        "interior_color": "Black Cloth",
        "drivetrain": "4x4",
        "transmission": "8-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "5.7L HEMI V8",
        "features": ["4x4", "HEMI V8", "Tow Package", "Air Suspension"],
        "description": "Ram 1500 Big Horn 4x4. HEMI V8 trade-in.",
        "image_url": "https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800",
    },
    {
        "stock_number": "FF-USED-506",
        "year": 2022,
        "make": "GMC",
        "model": "Sierra 1500",
        "trim": "Elevation 4x4",
        "body_style": "truck",
        "condition": "used",
        "mileage": 26000,
        "price": Decimal("44995.00"),
        "exterior_color": "Onyx Black",
        "interior_color": "Jet Black Cloth",
        "drivetrain": "4x4",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "5.3L V8",
        "features": ["4x4", "V8", "Tow Package"],
        "description": "Sierra 1500 Elevation 4x4 — blacked-out trim, 5.3L V8.",
        "image_url": "https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800",
    },
    {
        "stock_number": "FF-USED-507",
        "year": 2023,
        "make": "Toyota",
        "model": "Tacoma",
        "trim": "TRD Sport 4x4",
        "body_style": "truck",
        "condition": "used",
        "mileage": 15000,
        "price": Decimal("42995.00"),
        "exterior_color": "Lunar Rock",
        "interior_color": "Black Cloth",
        "drivetrain": "4x4",
        "transmission": "6-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "3.5L V6",
        "features": ["4x4", "TRD Sport", "Tow Package"],
        "description": "Tacoma TRD Sport 4x4 — popular off-road-tuned midsize truck.",
        "image_url": "https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800",
    },
    {
        "stock_number": "FF-USED-508",
        "year": 2022,
        "make": "Kia",
        "model": "Telluride",
        "trim": "EX AWD",
        "body_style": "suv",
        "condition": "used",
        "mileage": 30000,
        "price": Decimal("39995.00"),
        "exterior_color": "Wolf Gray",
        "interior_color": "Saddle Brown Leather",
        "drivetrain": "AWD",
        "transmission": "8-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "3.8L V6",
        "features": ["3rd Row", "Leather", "AWD", "Pano Roof"],
        "description": "Telluride EX AWD trade — three-row family SUV with leather.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
    {
        "stock_number": "FF-USED-509",
        "year": 2023,
        "make": "Ford",
        "model": "Bronco Sport",
        "trim": "Outer Banks AWD",
        "body_style": "suv",
        "condition": "certified",
        "mileage": 12000,
        "price": Decimal("38995.00"),
        "exterior_color": "Cyber Orange",
        "interior_color": "Roast Leather",
        "drivetrain": "AWD",
        "transmission": "8-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.0L EcoBoost I-4",
        "features": ["Leather", "AWD", "Pano Roof", "CPO Warranty"],
        "description": "Bronco Sport Outer Banks AWD CPO — well-equipped trail-styled crossover.",
        "image_url": "https://images.unsplash.com/photo-1629293363663-a7e8e9846a83?w=800",
    },
    {
        "stock_number": "FF-USED-510",
        "year": 2022,
        "make": "Ford",
        "model": "F-150",
        "trim": "STX 4x4",
        "body_style": "truck",
        "condition": "certified",
        "mileage": 35000,
        "price": Decimal("42995.00"),
        "exterior_color": "Carbonized Gray",
        "interior_color": "Medium Dark Slate Cloth",
        "drivetrain": "4x4",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.7L EcoBoost V6",
        "features": ["STX Appearance", "4x4", "Sync 4", "Tow Package", "CPO Warranty"],
        "description": "F-150 STX 4x4 CPO — sport appearance with 2.7L EcoBoost.",
        "image_url": "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800",
    },
    # ---- $50k+ band (premium / new flagship) ------------------------------
    {
        "stock_number": "FF-2024-601",
        "year": 2024,
        "make": "Chevrolet",
        "model": "Tahoe",
        "trim": "Z71 4WD",
        "body_style": "suv",
        "condition": "used",
        "mileage": 18000,
        "price": Decimal("58995.00"),
        "exterior_color": "Sterling Gray",
        "interior_color": "Jet Black Leather",
        "drivetrain": "4x4",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "5.3L V8",
        "features": ["4x4", "3rd Row", "Leather", "Tow Package"],
        "description": "Tahoe Z71 4WD trade — full-size three-row SUV with off-road package.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
    {
        "stock_number": "FF-2024-602",
        "year": 2024,
        "make": "GMC",
        "model": "Sierra 1500",
        "trim": "AT4 4x4",
        "body_style": "truck",
        "condition": "used",
        "mileage": 14000,
        "price": Decimal("59995.00"),
        "exterior_color": "Volcanic Red Tintcoat",
        "interior_color": "Jet Black Leather",
        "drivetrain": "4x4",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "5.3L V8",
        "features": ["AT4 Off-Road", "Leather", "4x4", "Tow Tech"],
        "description": "Sierra 1500 AT4 4x4 trade — off-road-tuned full-size with leather.",
        "image_url": "https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800",
    },
    {
        "stock_number": "FF-2024-603",
        "year": 2024,
        "make": "Ford",
        "model": "F-150",
        "trim": "King Ranch 4x4",
        "body_style": "truck",
        "condition": "new",
        "mileage": 8,
        "price": Decimal("74995.00"),
        "msrp": Decimal("76800.00"),
        "exterior_color": "Stone Gray",
        "interior_color": "Java Leather",
        "drivetrain": "4x4",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "3.5L EcoBoost V6",
        "features": ["King Ranch Leather", "BlueCruise", "Pano Roof", "B&O Audio", "Tow Tech"],
        "description": "Brand-new F-150 King Ranch — flagship trim, BlueCruise, B&O audio.",
        "image_url": "https://images.unsplash.com/photo-1571603375944-ed4f5b6f2632?w=800",
    },
    {
        "stock_number": "FF-2024-604",
        "year": 2024,
        "make": "Ram",
        "model": "1500",
        "trim": "Limited 4x4",
        "body_style": "truck",
        "condition": "used",
        "mileage": 12000,
        "price": Decimal("62995.00"),
        "exterior_color": "Granite Crystal",
        "interior_color": "Indigo Frost Leather",
        "drivetrain": "4x4",
        "transmission": "8-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "5.7L HEMI V8",
        "features": ["Limited Leather", "Air Suspension", "12-inch Display", "Tow Package"],
        "description": "Ram 1500 Limited 4x4 trade — top-trim with HEMI V8.",
        "image_url": "https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800",
    },
    {
        "stock_number": "FF-2024-605",
        "year": 2024,
        "make": "Toyota",
        "model": "Tundra",
        "trim": "Capstone 4x4",
        "body_style": "truck",
        "condition": "used",
        "mileage": 8000,
        "price": Decimal("74995.00"),
        "exterior_color": "Wind Chill Pearl",
        "interior_color": "American Walnut Leather",
        "drivetrain": "4x4",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Hybrid",
        "engine": "3.5L i-FORCE MAX Hybrid V6",
        "features": ["Hybrid", "Capstone Leather", "JBL Audio", "Pano Roof"],
        "description": "Tundra Capstone Hybrid 4x4 trade — flagship Toyota truck.",
        "image_url": "https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800",
    },
    {
        "stock_number": "FF-USED-606",
        "year": 2023,
        "make": "Jeep",
        "model": "Grand Cherokee",
        "trim": "Summit 4x4",
        "body_style": "suv",
        "condition": "used",
        "mileage": 18000,
        "price": Decimal("54995.00"),
        "exterior_color": "Velvet Red Pearl",
        "interior_color": "Tupelo Leather",
        "drivetrain": "4x4",
        "transmission": "8-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "5.7L HEMI V8",
        "features": ["4x4", "HEMI V8", "Summit Leather", "Quadra-Lift Air"],
        "description": "Grand Cherokee Summit 4x4 trade — top-trim with HEMI V8 and air suspension.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
    # ====================================================================
    # Phase 8m — expanded inventory (55 → 90 vehicles).
    # Adds: Super Duty + Lightning + Transit (new Ford), CPO depth, used
    # hybrids/EVs, minivans, 3-row family SUVs, more competitor cross-shop.
    # ====================================================================
    # ---- Phase 8m: new Ford (+11) ---------------------------------------
    {
        "stock_number": "FF-2025-011",
        "year": 2025,
        "make": "Ford",
        "model": "F-150 Lightning",
        "trim": "XLT Extended Range",
        "body_style": "ev",
        "condition": "new",
        "mileage": 9,
        "price": Decimal("66995.00"),
        "msrp": Decimal("68500.00"),
        "exterior_color": "Atlas Blue",
        "interior_color": "Medium Dark Slate",
        "drivetrain": "AWD",
        "transmission": "Single-Speed EV",
        "fuel_type": "Electric",
        "engine": "Dual-Motor AWD, 131 kWh Extended Range",
        "features": ["EV", "AWD", "BlueCruise", "Pro Power Onboard", "Sync 4", "Tow Package"],
        "description": "All-electric F-150 Lightning XLT with the extended-range battery (~320 mile range), Pro Power Onboard, and BlueCruise hands-free driving.",
        "image_url": "https://images.unsplash.com/photo-1633509817627-f5fadccd5045?w=800",
    },
    {
        "stock_number": "FF-2025-012",
        "year": 2025,
        "make": "Ford",
        "model": "F-250 Super Duty",
        "trim": "XLT Crew Cab 4x4",
        "body_style": "truck",
        "condition": "new",
        "mileage": 6,
        "price": Decimal("73995.00"),
        "msrp": Decimal("75900.00"),
        "exterior_color": "Agate Black",
        "interior_color": "Medium Dark Slate",
        "drivetrain": "4x4",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Diesel",
        "engine": "6.7L Power Stroke V8 Turbo Diesel",
        "features": ["Diesel", "Tow Tech", "FX4 Off-Road", "Sync 4", "Trailer Brake"],
        "description": "Super Duty F-250 XLT with the 6.7L Power Stroke diesel — built for fifth-wheel and gooseneck towing.",
        "image_url": "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800",
    },
    {
        "stock_number": "FF-2025-013",
        "year": 2025,
        "make": "Ford",
        "model": "F-350 Super Duty",
        "trim": "Lariat Crew Cab 4x4",
        "body_style": "truck",
        "condition": "new",
        "mileage": 7,
        "price": Decimal("81995.00"),
        "msrp": Decimal("83800.00"),
        "exterior_color": "Stone Gray",
        "interior_color": "Black Leather",
        "drivetrain": "4x4",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Diesel",
        "engine": "6.7L Power Stroke V8 Turbo Diesel",
        "features": ["Diesel", "Lariat Leather", "Tow Tech", "BlueCruise", "Pano Roof"],
        "description": "F-350 Super Duty Lariat with the 6.7L Power Stroke and BlueCruise — flagship work-and-tow truck.",
        "image_url": "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800",
    },
    {
        "stock_number": "FF-2025-014",
        "year": 2025,
        "make": "Ford",
        "model": "Expedition",
        "trim": "XLT 4x4",
        "body_style": "suv",
        "condition": "new",
        "mileage": 10,
        "price": Decimal("64995.00"),
        "msrp": Decimal("66500.00"),
        "exterior_color": "Carbonized Gray",
        "interior_color": "Medium Stone",
        "drivetrain": "4x4",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "3.5L EcoBoost V6",
        "features": ["3rd Row", "4x4", "Tow Package", "Sync 4", "Adaptive Cruise"],
        "description": "Full-size three-row Expedition XLT 4x4 — built for big families and big tow jobs.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
    {
        "stock_number": "FF-2025-015",
        "year": 2025,
        "make": "Ford",
        "model": "Transit-350",
        "trim": "Cargo Van Medium Roof",
        "body_style": "van",
        "condition": "new",
        "mileage": 11,
        "price": Decimal("53995.00"),
        "msrp": Decimal("55400.00"),
        "exterior_color": "Oxford White",
        "interior_color": "Pewter Vinyl",
        "drivetrain": "RWD",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "3.5L EcoBoost V6",
        "features": ["Cargo Van", "Sync 4", "Backup Camera", "Lane Assist"],
        "description": "Transit-350 cargo van with medium roof — purpose-built for trades, deliveries, and small-business fleet.",
        "image_url": "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800",
    },
    {
        "stock_number": "FF-2025-016",
        "year": 2025,
        "make": "Ford",
        "model": "Transit-150",
        "trim": "Crew Van XLT",
        "body_style": "van",
        "condition": "new",
        "mileage": 9,
        "price": Decimal("51995.00"),
        "msrp": Decimal("53400.00"),
        "exterior_color": "Magnetic",
        "interior_color": "Medium Stone Cloth",
        "drivetrain": "RWD",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "3.5L EcoBoost V6",
        "features": ["Crew Van", "Sync 4", "5-Passenger", "Cargo Partition"],
        "description": "Transit-150 crew van — five seats up front, cargo space in back. Versatile for service crews.",
        "image_url": "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800",
    },
    {
        "stock_number": "FF-2025-017",
        "year": 2025,
        "make": "Ford",
        "model": "Transit Passenger Wagon",
        "trim": "XLT Medium Roof",
        "body_style": "van",
        "condition": "new",
        "mileage": 12,
        "price": Decimal("57995.00"),
        "msrp": Decimal("59500.00"),
        "exterior_color": "Iconic Silver",
        "interior_color": "Ebony Cloth",
        "drivetrain": "RWD",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "3.5L EcoBoost V6",
        "features": ["12-Passenger", "Sync 4", "Adaptive Cruise", "Lane Assist"],
        "description": "12-passenger Transit Wagon XLT — shuttle, church, large-family, and tour duty.",
        "image_url": "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800",
    },
    {
        "stock_number": "FF-2025-018",
        "year": 2025,
        "make": "Ford",
        "model": "Maverick",
        "trim": "Lariat Hybrid AWD SuperCrew",
        "body_style": "truck",
        "condition": "new",
        "mileage": 10,
        "price": Decimal("37995.00"),
        "msrp": Decimal("38800.00"),
        "exterior_color": "Cactus Gray",
        "interior_color": "Black Leather",
        "drivetrain": "AWD",
        "transmission": "eCVT",
        "fuel_type": "Hybrid",
        "engine": "2.5L iVCT Atkinson Hybrid",
        "features": ["Hybrid", "AWD", "Leather", "Sync 4", "FlexBed"],
        "description": "Top-trim Maverick Lariat Hybrid with AWD and leather — efficient compact pickup with creature comforts.",
        "image_url": "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=800",
    },
    {
        "stock_number": "FF-2025-019",
        "year": 2025,
        "make": "Ford",
        "model": "Escape",
        "trim": "Active Hybrid AWD",
        "body_style": "suv",
        "condition": "new",
        "mileage": 11,
        "price": Decimal("32495.00"),
        "msrp": Decimal("33200.00"),
        "exterior_color": "Atlas Blue",
        "interior_color": "Ebony Cloth",
        "drivetrain": "AWD",
        "transmission": "eCVT",
        "fuel_type": "Hybrid",
        "engine": "2.5L iVCT Atkinson Hybrid",
        "features": ["Hybrid", "AWD", "Sync 4", "Heated Seats", "Adaptive Cruise"],
        "description": "Compact Escape Hybrid AWD — ~37 mpg combined with all-weather traction. New-Ford option in the $30k band.",
        "image_url": "https://images.unsplash.com/photo-1591293836027-e05b48473b67?w=800",
    },
    {
        "stock_number": "FF-2025-020",
        "year": 2025,
        "make": "Ford",
        "model": "F-150",
        "trim": "STX SuperCrew 4x4",
        "body_style": "truck",
        "condition": "new",
        "mileage": 8,
        "price": Decimal("52995.00"),
        "msrp": Decimal("54200.00"),
        "exterior_color": "Velocity Blue",
        "interior_color": "Medium Dark Slate",
        "drivetrain": "4x4",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.7L EcoBoost V6",
        "features": ["STX Appearance", "4x4", "Tow Package", "Sync 4"],
        "description": "F-150 STX SuperCrew 4x4 with 2.7L EcoBoost — sport-styled mid-trim new F-150.",
        "image_url": "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800",
    },
    {
        "stock_number": "FF-2025-021",
        "year": 2025,
        "make": "Ford",
        "model": "Mustang",
        "trim": "EcoBoost Premium Fastback",
        "body_style": "car",
        "condition": "new",
        "mileage": 12,
        "price": Decimal("35995.00"),
        "msrp": Decimal("36800.00"),
        "exterior_color": "Vapor Blue",
        "interior_color": "Black ActiveX",
        "drivetrain": "RWD",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.3L EcoBoost I-4",
        "features": ["Premium Pkg", "Sync 4", "B&O Audio", "Active Exhaust"],
        "description": "Mustang EcoBoost Premium Fastback — turbo-four sports coupe, the entry door to the new pony.",
        "image_url": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800",
    },
    # ---- Phase 8m: certified pre-owned Ford (+7) ------------------------
    {
        "stock_number": "FF-USED-110",
        "year": 2022,
        "make": "Ford",
        "model": "F-150",
        "trim": "PowerBoost Hybrid Lariat 4x4",
        "body_style": "truck",
        "condition": "certified",
        "mileage": 32000,
        "price": Decimal("47995.00"),
        "exterior_color": "Antimatter Blue",
        "interior_color": "Black Leather",
        "drivetrain": "4x4",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Hybrid",
        "engine": "3.5L PowerBoost Full-Hybrid V6",
        "features": ["Hybrid", "4x4", "Leather", "Pro Power Onboard", "Sync 4", "CPO Warranty"],
        "description": "Certified F-150 PowerBoost Hybrid Lariat 4x4 — full hybrid V6 with Pro Power Onboard generator.",
        "image_url": "https://images.unsplash.com/photo-1571603375944-ed4f5b6f2632?w=800",
    },
    {
        "stock_number": "FF-USED-111",
        "year": 2023,
        "make": "Ford",
        "model": "Explorer",
        "trim": "ST AWD",
        "body_style": "suv",
        "condition": "certified",
        "mileage": 22000,
        "price": Decimal("45995.00"),
        "exterior_color": "Rapid Red",
        "interior_color": "Black ActiveX",
        "drivetrain": "AWD",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "3.0L EcoBoost V6",
        "features": ["3rd Row", "ST Performance", "AWD", "Pano Roof", "B&O Audio", "CPO Warranty"],
        "description": "Certified Explorer ST AWD — 400-hp three-row family SUV with the performance-tuned ST package.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
    {
        "stock_number": "FF-USED-112",
        "year": 2023,
        "make": "Ford",
        "model": "Mustang Mach-E",
        "trim": "Premium AWD Extended Range",
        "body_style": "ev",
        "condition": "certified",
        "mileage": 18000,
        "price": Decimal("41995.00"),
        "exterior_color": "Star White",
        "interior_color": "Black ActiveX",
        "drivetrain": "AWD",
        "transmission": "Single-Speed EV",
        "fuel_type": "Electric",
        "engine": "Dual-Motor AWD, 91 kWh Extended Range",
        "features": ["AWD EV", "BlueCruise", "Pano Roof", "B&O Audio", "DC Fast Charge", "CPO Warranty"],
        "description": "Certified Mach-E Premium AWD ER — dual motor, ~290 mile range, BlueCruise hands-free highway.",
        "image_url": "https://images.unsplash.com/photo-1633509817627-f5fadccd5045?w=800",
    },
    {
        "stock_number": "FF-USED-113",
        "year": 2022,
        "make": "Ford",
        "model": "Maverick",
        "trim": "XLT Hybrid SuperCrew",
        "body_style": "truck",
        "condition": "certified",
        "mileage": 28000,
        "price": Decimal("27995.00"),
        "exterior_color": "Area 51",
        "interior_color": "Black Cloth",
        "drivetrain": "FWD",
        "transmission": "eCVT",
        "fuel_type": "Hybrid",
        "engine": "2.5L iVCT Atkinson Hybrid",
        "features": ["Hybrid", "FlexBed", "Sync 3", "CPO Warranty"],
        "description": "Certified Maverick XLT Hybrid — affordable certified compact pickup, ~42 mpg city.",
        "image_url": "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=800",
    },
    {
        "stock_number": "FF-USED-114",
        "year": 2023,
        "make": "Ford",
        "model": "Bronco",
        "trim": "Black Diamond 4-Door",
        "body_style": "suv",
        "condition": "certified",
        "mileage": 21000,
        "price": Decimal("44995.00"),
        "exterior_color": "Shadow Black",
        "interior_color": "Black Marine-Grade Vinyl",
        "drivetrain": "4x4",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.3L EcoBoost I-4",
        "features": ["Removable Top", "Rock Rails", "4x4", "Trail Modes", "CPO Warranty"],
        "description": "Certified Bronco Black Diamond 4-Door — purpose-built off-road trim with rock rails and marine vinyl.",
        "image_url": "https://images.unsplash.com/photo-1632245889029-e406faaa34cd?w=800",
    },
    {
        "stock_number": "FF-USED-115",
        "year": 2022,
        "make": "Ford",
        "model": "F-250 Super Duty",
        "trim": "Lariat Crew Cab 4x4",
        "body_style": "truck",
        "condition": "certified",
        "mileage": 35000,
        "price": Decimal("57995.00"),
        "exterior_color": "Magnetic",
        "interior_color": "Black Leather",
        "drivetrain": "4x4",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Diesel",
        "engine": "6.7L Power Stroke V8 Turbo Diesel",
        "features": ["Diesel", "4x4", "Lariat Leather", "Tow Tech", "CPO Warranty"],
        "description": "Certified F-250 Super Duty Lariat 4x4 with the 6.7L Power Stroke — heavy-duty diesel with Ford CPO coverage.",
        "image_url": "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800",
    },
    {
        "stock_number": "FF-USED-116",
        "year": 2023,
        "make": "Ford",
        "model": "Edge",
        "trim": "ST AWD",
        "body_style": "suv",
        "condition": "certified",
        "mileage": 24000,
        "price": Decimal("32995.00"),
        "exterior_color": "Atlas Blue",
        "interior_color": "Ebony Leather",
        "drivetrain": "AWD",
        "transmission": "8-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.7L EcoBoost V6",
        "features": ["ST Performance", "AWD", "Leather", "Pano Roof", "B&O Audio", "CPO Warranty"],
        "description": "Certified Edge ST AWD — performance-tuned crossover with 335 hp and panoramic roof.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
    # ---- Phase 8m: used multi-brand trade-ins (+17) ---------------------
    {
        "stock_number": "FF-USED-206",
        "year": 2017,
        "make": "Hyundai",
        "model": "Sonata",
        "trim": "SE",
        "body_style": "car",
        "condition": "used",
        "mileage": 98000,
        "price": Decimal("10995.00"),
        "exterior_color": "Phantom Black",
        "interior_color": "Gray Cloth",
        "drivetrain": "FWD",
        "transmission": "6-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.4L I-4",
        "features": ["Bluetooth", "Backup Camera", "Cruise Control"],
        "description": "Used Hyundai Sonata SE — under $11k commuter sedan with proven reliability.",
        "image_url": "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800",
    },
    {
        "stock_number": "FF-USED-309",
        "year": 2018,
        "make": "Subaru",
        "model": "Outback",
        "trim": "2.5i Premium",
        "body_style": "suv",
        "condition": "used",
        "mileage": 82000,
        "price": Decimal("17995.00"),
        "exterior_color": "Crystal White Pearl",
        "interior_color": "Slate Black Cloth",
        "drivetrain": "AWD",
        "transmission": "CVT",
        "fuel_type": "Gasoline",
        "engine": "2.5L Boxer I-4",
        "features": ["AWD", "Heated Seats", "Backup Camera", "Roof Rails"],
        "description": "Outback 2.5i Premium AWD — adventure-friendly wagon with all-weather traction.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
    {
        "stock_number": "FF-USED-310",
        "year": 2019,
        "make": "Subaru",
        "model": "Forester",
        "trim": "Premium AWD",
        "body_style": "suv",
        "condition": "used",
        "mileage": 68000,
        "price": Decimal("18995.00"),
        "exterior_color": "Magnetite Gray",
        "interior_color": "Slate Black Cloth",
        "drivetrain": "AWD",
        "transmission": "CVT",
        "fuel_type": "Gasoline",
        "engine": "2.5L Boxer I-4",
        "features": ["AWD", "EyeSight", "Pano Roof", "Heated Seats"],
        "description": "Forester Premium AWD with EyeSight safety suite — popular all-weather compact SUV trade-in.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
    {
        "stock_number": "FF-USED-311",
        "year": 2018,
        "make": "Toyota",
        "model": "Highlander",
        "trim": "LE AWD",
        "body_style": "suv",
        "condition": "used",
        "mileage": 76000,
        "price": Decimal("22995.00"),
        "exterior_color": "Predawn Gray Mica",
        "interior_color": "Ash Cloth",
        "drivetrain": "AWD",
        "transmission": "8-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "3.5L V6",
        "features": ["3rd Row", "AWD", "Backup Camera", "Lane Assist"],
        "description": "Highlander LE AWD — popular three-row family SUV trade-in under $23k.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
    {
        "stock_number": "FF-USED-312",
        "year": 2021,
        "make": "Mazda",
        "model": "CX-5",
        "trim": "Touring AWD",
        "body_style": "suv",
        "condition": "used",
        "mileage": 38000,
        "price": Decimal("23995.00"),
        "exterior_color": "Soul Red Crystal",
        "interior_color": "Black Leatherette",
        "drivetrain": "AWD",
        "transmission": "6-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "2.5L SkyActiv I-4",
        "features": ["AWD", "Leatherette", "Heated Seats", "Adaptive Cruise"],
        "description": "CX-5 Touring AWD — premium-feel compact SUV with sharp styling.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
    {
        "stock_number": "FF-USED-313",
        "year": 2018,
        "make": "Honda",
        "model": "Odyssey",
        "trim": "EX-L",
        "body_style": "van",
        "condition": "used",
        "mileage": 88000,
        "price": Decimal("17995.00"),
        "exterior_color": "Modern Steel",
        "interior_color": "Mocha Leather",
        "drivetrain": "FWD",
        "transmission": "9-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "3.5L V6",
        "features": ["8-Passenger", "Leather", "Power Sliding Doors", "Magic Slide Seats"],
        "description": "Odyssey EX-L minivan — leather, power sliding doors, family-friendly trade-in.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
    {
        "stock_number": "FF-USED-314",
        "year": 2018,
        "make": "Chrysler",
        "model": "Pacifica",
        "trim": "Touring L",
        "body_style": "van",
        "condition": "used",
        "mileage": 92000,
        "price": Decimal("18495.00"),
        "exterior_color": "Brilliant Black",
        "interior_color": "Black Leather",
        "drivetrain": "FWD",
        "transmission": "9-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "3.6L Pentastar V6",
        "features": ["Stow 'n Go", "Leather", "Tri-Zone Climate", "Backup Camera"],
        "description": "Pacifica Touring L — Stow 'n Go seats, leather, premium minivan trade.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
    {
        "stock_number": "FF-USED-411",
        "year": 2021,
        "make": "Toyota",
        "model": "Highlander",
        "trim": "XLE AWD",
        "body_style": "suv",
        "condition": "used",
        "mileage": 38000,
        "price": Decimal("31995.00"),
        "exterior_color": "Celestial Silver",
        "interior_color": "Graphite Leather",
        "drivetrain": "AWD",
        "transmission": "8-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "3.5L V6",
        "features": ["3rd Row", "AWD", "Leather", "Sunroof", "Adaptive Cruise"],
        "description": "Highlander XLE AWD — three-row family SUV with leather and sunroof.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
    {
        "stock_number": "FF-USED-412",
        "year": 2020,
        "make": "Honda",
        "model": "Pilot",
        "trim": "EX-L AWD",
        "body_style": "suv",
        "condition": "used",
        "mileage": 52000,
        "price": Decimal("29995.00"),
        "exterior_color": "Lunar Silver",
        "interior_color": "Beige Leather",
        "drivetrain": "AWD",
        "transmission": "9-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "3.5L V6",
        "features": ["3rd Row", "AWD", "Leather", "Sunroof", "Heated Seats"],
        "description": "Pilot EX-L AWD trade — eight-passenger family SUV with leather.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
    {
        "stock_number": "FF-USED-413",
        "year": 2022,
        "make": "Hyundai",
        "model": "Tucson",
        "trim": "SEL Hybrid AWD",
        "body_style": "suv",
        "condition": "used",
        "mileage": 28000,
        "price": Decimal("27995.00"),
        "exterior_color": "Shimmering Silver",
        "interior_color": "Black Cloth",
        "drivetrain": "AWD",
        "transmission": "6-Speed Automatic",
        "fuel_type": "Hybrid",
        "engine": "1.6L Turbo Hybrid I-4",
        "features": ["Hybrid", "AWD", "Heated Seats", "Adaptive Cruise"],
        "description": "Tucson SEL Hybrid AWD — efficient compact SUV trade-in, ~37 mpg combined.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
    {
        "stock_number": "FF-USED-414",
        "year": 2020,
        "make": "Toyota",
        "model": "4Runner",
        "trim": "SR5 4WD",
        "body_style": "suv",
        "condition": "used",
        "mileage": 62000,
        "price": Decimal("33995.00"),
        "exterior_color": "Magnetic Gray",
        "interior_color": "Sand Beige Cloth",
        "drivetrain": "4x4",
        "transmission": "5-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "4.0L V6",
        "features": ["4x4", "Tow Package", "Backup Camera", "Crawl Control"],
        "description": "4Runner SR5 4WD — body-on-frame midsize SUV trade for off-road and tow duty.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
    {
        "stock_number": "FF-USED-415",
        "year": 2022,
        "make": "Tesla",
        "model": "Model 3",
        "trim": "Long Range AWD",
        "body_style": "ev",
        "condition": "used",
        "mileage": 34000,
        "price": Decimal("31995.00"),
        "exterior_color": "Pearl White",
        "interior_color": "Black Vegan Leather",
        "drivetrain": "AWD",
        "transmission": "Single-Speed EV",
        "fuel_type": "Electric",
        "engine": "Dual-Motor AWD, 82 kWh",
        "features": ["AWD EV", "Autopilot", "Glass Roof", "Supercharger Access"],
        "description": "Tesla Model 3 Long Range AWD trade — ~330 mile range, dual-motor sedan.",
        "image_url": "https://images.unsplash.com/photo-1633509817627-f5fadccd5045?w=800",
    },
    {
        "stock_number": "FF-USED-416",
        "year": 2021,
        "make": "Hyundai",
        "model": "Ioniq 5",
        "trim": "SEL AWD",
        "body_style": "ev",
        "condition": "used",
        "mileage": 30000,
        "price": Decimal("32995.00"),
        "exterior_color": "Lucid Blue Pearl",
        "interior_color": "Dark Pebble Gray",
        "drivetrain": "AWD",
        "transmission": "Single-Speed EV",
        "fuel_type": "Electric",
        "engine": "Dual-Motor AWD, 77.4 kWh",
        "features": ["AWD EV", "DC Fast Charge", "Vehicle-to-Load", "Heated Seats"],
        "description": "Ioniq 5 SEL AWD trade — retro-styled crossover EV with ~256 mile range.",
        "image_url": "https://images.unsplash.com/photo-1633509817627-f5fadccd5045?w=800",
    },
    {
        "stock_number": "FF-USED-417",
        "year": 2022,
        "make": "Kia",
        "model": "EV6",
        "trim": "Wind AWD",
        "body_style": "ev",
        "condition": "used",
        "mileage": 26000,
        "price": Decimal("27995.00"),
        "exterior_color": "Glacier",
        "interior_color": "Black Cloth/Vegan Leather",
        "drivetrain": "AWD",
        "transmission": "Single-Speed EV",
        "fuel_type": "Electric",
        "engine": "Dual-Motor AWD, 77.4 kWh",
        "features": ["AWD EV", "DC Fast Charge", "Heated Seats", "Highway Driving Assist"],
        "description": "Kia EV6 Wind AWD trade — ~274 mile range, fast 350 kW DC charging capability.",
        "image_url": "https://images.unsplash.com/photo-1633509817627-f5fadccd5045?w=800",
    },
    {
        "stock_number": "FF-USED-511",
        "year": 2018,
        "make": "Toyota",
        "model": "Tundra",
        "trim": "Limited CrewMax 4x4",
        "body_style": "truck",
        "condition": "used",
        "mileage": 78000,
        "price": Decimal("35995.00"),
        "exterior_color": "Super White",
        "interior_color": "Graphite Leather",
        "drivetrain": "4x4",
        "transmission": "6-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "5.7L i-FORCE V8",
        "features": ["4x4", "Leather", "Tow Package", "Sunroof"],
        "description": "Tundra Limited CrewMax 4x4 — full-size Toyota trade with leather and 5.7L V8.",
        "image_url": "https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800",
    },
    {
        "stock_number": "FF-USED-512",
        "year": 2020,
        "make": "Ram",
        "model": "2500",
        "trim": "Tradesman Crew Cab 4x4",
        "body_style": "truck",
        "condition": "used",
        "mileage": 65000,
        "price": Decimal("47995.00"),
        "exterior_color": "Bright White",
        "interior_color": "Diesel Gray Cloth",
        "drivetrain": "4x4",
        "transmission": "6-Speed Automatic",
        "fuel_type": "Diesel",
        "engine": "6.7L Cummins Turbo Diesel I-6",
        "features": ["Cummins Diesel", "4x4", "Tow Package", "Trailer Brake"],
        "description": "Ram 2500 Tradesman 4x4 with the 6.7L Cummins — used heavy-duty diesel work truck.",
        "image_url": "https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800",
    },
    {
        "stock_number": "FF-USED-607",
        "year": 2021,
        "make": "Chevrolet",
        "model": "Tahoe",
        "trim": "LT 4WD",
        "body_style": "suv",
        "condition": "used",
        "mileage": 42000,
        "price": Decimal("42995.00"),
        "exterior_color": "Black",
        "interior_color": "Jet Black Leather",
        "drivetrain": "4x4",
        "transmission": "10-Speed Automatic",
        "fuel_type": "Gasoline",
        "engine": "5.3L V8",
        "features": ["3rd Row", "4x4", "Leather", "Tow Package"],
        "description": "Tahoe LT 4WD trade — full-size three-row SUV with leather and 5.3L V8.",
        "image_url": "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    },
]


class Command(BaseCommand):
    help = "Seed the database with demo Ford vehicles for the dealer AI MVP."

    def add_arguments(self, parser):
        parser.add_argument(
            "--reset",
            action="store_true",
            help="Delete existing demo vehicles (by stock prefix) before seeding.",
        )

    def handle(self, *args, **options):
        if options["reset"]:
            qs = Vehicle.objects.filter(stock_number__startswith="FF-")
            count = qs.count()
            qs.delete()
            self.stdout.write(self.style.WARNING(f"Deleted {count} existing demo vehicles."))

        created = 0
        updated = 0
        now = timezone.now()
        for spec in DEMO_VEHICLES:
            stock = spec["stock_number"]
            defaults = {**spec, "source": DEMO_SOURCE, "last_seen_at": now}
            obj, was_created = Vehicle.objects.update_or_create(
                stock_number=stock, defaults=defaults
            )
            if was_created:
                obj.imported_at = now
                obj.save(update_fields=["imported_at"])
                created += 1
            else:
                updated += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Seed complete — {created} created, {updated} updated."
            )
        )
