# Generated by Django 5.0.6 on 2026-04-30 22:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("customer_name", models.CharField(blank=True, max_length=128)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                ("customer_phone", models.CharField(blank=True, max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("extracted_profile", models.JSONField(blank=True, default=dict)),
                ("lead_created", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_number", models.CharField(max_length=32, unique=True)),
                ("vin", models.CharField(blank=True, max_length=32)),
                ("year", models.PositiveIntegerField()),
                ("make", models.CharField(default="Ford", max_length=64)),
                ("model", models.CharField(max_length=64)),
                ("trim", models.CharField(blank=True, max_length=128)),
                (
                    "body_style",
                    models.CharField(
                        choices=[
                            ("truck", "Truck"),
                            ("suv", "SUV"),
                            ("car", "Car"),
                            ("ev", "EV"),
                            ("van", "Van"),
                        ],
                        default="suv",
                        max_length=16,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("used", "Used"),
                            ("certified", "Certified Pre-Owned"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("mileage", models.PositiveIntegerField(default=0)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "msrp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("exterior_color", models.CharField(blank=True, max_length=64)),
                ("interior_color", models.CharField(blank=True, max_length=64)),
                ("drivetrain", models.CharField(blank=True, max_length=32)),
                ("transmission", models.CharField(blank=True, max_length=32)),
                (
                    "fuel_type",
                    models.CharField(blank=True, default="Gasoline", max_length=32),
                ),
                ("engine", models.CharField(blank=True, max_length=128)),
                ("features", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-year", "model"],
            },
        ),
        migrations.CreateModel(
            name="CustomerLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "target_monthly_payment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "down_payment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("trade_in", models.CharField(blank=True, max_length=255)),
                (
                    "urgency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("immediate", "Buying now"),
                            ("this_week", "This week"),
                            ("this_month", "This month"),
                            ("researching", "Just researching"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("credit_range", models.CharField(blank=True, max_length=64)),
                ("conversation_summary", models.TextField(blank=True)),
                ("recommended_next_action", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("handed_off", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="dealer_ai.chatsession",
                    ),
                ),
                (
                    "interested_vehicles",
                    models.ManyToManyField(
                        blank=True, related_name="leads", to="dealer_ai.vehicle"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("tool", "Tool"),
                        ],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="dealer_ai.chatsession",
                    ),
                ),
                (
                    "matched_vehicles",
                    models.ManyToManyField(
                        blank=True, related_name="chat_mentions", to="dealer_ai.vehicle"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
