# Generated by Django 5.0.6 on 2026-04-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_ai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="imported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="source",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
