# Generated by Django 5.0.6 on 2026-05-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_ai", "0003_salesperson_customerlead_assigned_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DealerOnboardingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dealership_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "store_location",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "main_brands",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "sales_phone",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("website", models.CharField(blank=True, default="", max_length=255)),
                (
                    "sales_tone",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "pricing_comfort",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "appointment_preference",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "lead_handoff_style",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "salesperson_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "salesperson_role",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "salesperson_phone",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "salesperson_email",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "salesperson_specialties",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "salesperson_preferred_tone",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("salesperson_intro", models.TextField(blank=True, default="")),
                ("dealership_greeting", models.TextField(blank=True, default="")),
                ("approved_phrases", models.TextField(blank=True, default="")),
                ("banned_phrases", models.TextField(blank=True, default="")),
                ("escalation_rule", models.TextField(blank=True, default="")),
                ("payment_disclaimer", models.TextField(blank=True, default="")),
                ("inventory_connected", models.BooleanField(default=False)),
                ("finance_rules_reviewed", models.BooleanField(default=False)),
                ("salespeople_added", models.BooleanField(default=False)),
                ("demo_prompts_tested", models.BooleanField(default=False)),
                ("pilot_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
