# Generated by Django 5.0.6 on 2026-05-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_ai", "0004_dealeronboardingprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealeronboardingprofile",
            name="logo_url",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
    ]
