# Generated by Django 5.0.6 on 2026-07-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_ai", "0005_dealeronboardingprofile_logo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealeronboardingprofile",
            name="bhph_configured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dealeronboardingprofile",
            name="bhph_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="dealeronboardingprofile",
            name="credit_range_served",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="dealeronboardingprofile",
            name="dealer_type",
            field=models.CharField(
                blank=True,
                choices=[("independent", "Independent"), ("franchise", "Franchise")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dealeronboardingprofile",
            name="floor_plan_lender",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="dealeronboardingprofile",
            name="makes_carried",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="dealeronboardingprofile",
            name="subprime_lenders",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="dealeronboardingprofile",
            name="warranty_offering",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
