# Generated by Django 5.0.6 on 2026-07-31 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_ai", "0007_dealership"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="dealership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to="dealer_ai.dealership",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="dealership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to="dealer_ai.dealership",
            ),
        ),
        migrations.AddField(
            model_name="customerlead",
            name="dealership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_leads",
                to="dealer_ai.dealership",
            ),
        ),
        migrations.AddField(
            model_name="dealeronboardingprofile",
            name="dealership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="onboarding_profiles",
                to="dealer_ai.dealership",
            ),
        ),
        migrations.AddField(
            model_name="salesperson",
            name="dealership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salespeople",
                to="dealer_ai.dealership",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="dealership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicles",
                to="dealer_ai.dealership",
            ),
        ),
    ]
