# Generated by Django 5.0.6 on 2026-08-01 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_ai", "0011_userdealershiprole_and_salesperson_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleAcquisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("auction", "Auction"),
                            ("trade", "Trade-in"),
                            ("wholesale", "Wholesale (dealer-to-dealer)"),
                            ("private", "Private party"),
                            ("off_lease", "Off-lease"),
                            ("rental", "Rental return"),
                            ("repo", "Repossession"),
                            ("fleet", "Fleet disposal"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "source_detail",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("purchase_date", models.DateField()),
                (
                    "buyer_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "arbitration_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "transportation_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "title_acquisition_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dealership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_acquisitions",
                        to="dealer_ai.dealership",
                    ),
                ),
                (
                    "vehicle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acquisition",
                        to="dealer_ai.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle acquisition",
                "verbose_name_plural": "Vehicle acquisitions",
                "ordering": ("-purchase_date", "-created_at"),
            },
        ),
    ]
