# Generated by Django 5.0.6 on 2026-08-01 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_ai", "0012_vehicleacquisition"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("floor_plan_interest", "Floor plan interest"),
                            ("floor_plan_fees", "Floor plan fees"),
                            ("curtailment", "Curtailment"),
                            ("wire_fees", "Wire fees"),
                            ("banking_fees", "Banking fees"),
                            ("parts", "Parts"),
                            ("mechanical_labor", "Mechanical labor"),
                            ("tires", "Tires"),
                            ("brakes", "Brakes"),
                            ("battery", "Battery"),
                            ("oil_service", "Oil service"),
                            ("diagnostics", "Diagnostics"),
                            ("glass", "Glass"),
                            ("body_work", "Body work"),
                            ("paint", "Paint"),
                            ("upholstery", "Upholstery"),
                            ("wheel_repair", "Wheel repair"),
                            ("detail", "Detail"),
                            ("fuel", "Fuel"),
                            ("listing_fees", "Listing fees"),
                            ("advertising_allocation", "Advertising allocation"),
                            ("registration", "Registration"),
                            ("title_work", "Title work"),
                            ("shipping", "Shipping"),
                            ("misc_dealer_expenses", "Miscellaneous dealer expenses"),
                            ("photography", "Photography"),
                        ],
                        max_length=32,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("incurred_at", models.DateTimeField()),
                ("vendor", models.CharField(blank=True, default="", max_length=255)),
                ("reference", models.CharField(blank=True, default="", max_length=128)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_estimate", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dealership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_costs",
                        to="dealer_ai.dealership",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="dealer_ai.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle cost",
                "verbose_name_plural": "Vehicle costs",
                "ordering": ("-incurred_at", "-created_at"),
            },
        ),
    ]
