# Generated by Django 5.0.6 on 2026-08-01 03:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_ai", "0014_onboardingprofile_floor_plan_apr"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConditionFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("mechanical", "Mechanical"),
                            ("cosmetic", "Cosmetic / paint"),
                            ("body", "Body / structural"),
                            ("glass", "Glass"),
                            ("tires", "Tires"),
                            ("interior", "Interior"),
                            ("fluids", "Fluids"),
                            ("electrical", "Electrical"),
                            ("safety", "Safety"),
                            ("accessories", "Accessories / features present"),
                            ("missing", "Missing items"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("advisory", "Advisory"),
                            ("recommended", "Recommended"),
                            ("required", "Required"),
                            ("safety", "Safety"),
                        ],
                        max_length=16,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dealership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condition_findings",
                        to="dealer_ai.dealership",
                    ),
                ),
            ],
            options={
                "verbose_name": "Condition finding",
                "verbose_name_plural": "Condition findings",
                "ordering": ("severity", "category", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="ConditionFindingPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("storage_key", models.CharField(max_length=512, unique=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("image/jpeg", "JPEG"),
                            ("image/png", "PNG"),
                            ("image/heic", "HEIC"),
                            ("image/webp", "WEBP"),
                        ],
                        max_length=32,
                    ),
                ),
                ("size_bytes", models.PositiveIntegerField()),
                ("caption", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dealership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condition_finding_photos",
                        to="dealer_ai.dealership",
                    ),
                ),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="dealer_ai.conditionfinding",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Condition finding photo",
                "verbose_name_plural": "Condition finding photos",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="ConditionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inspector_name", models.CharField(max_length=255)),
                ("inspected_at", models.DateTimeField()),
                ("mileage_at_inspection", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("complete", "Complete")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dealership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condition_reports",
                        to="dealer_ai.dealership",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condition_reports",
                        to="dealer_ai.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Condition report",
                "verbose_name_plural": "Condition reports",
                "ordering": ("-inspected_at", "-created_at"),
            },
        ),
        migrations.AddField(
            model_name="conditionfinding",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="findings",
                to="dealer_ai.conditionreport",
            ),
        ),
    ]
