# Generated by Django 5.0.6 on 2026-08-02 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_ai", "0037_m121_bhph_note_entity"),
    ]

    operations = [
        migrations.CreateModel(
            name="BhphPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        help_text="Operator-supplied receipt timestamp for the payment."
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("check", "Check"),
                            ("debit", "Debit card"),
                            ("ach", "ACH"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "applied_to_fees",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "applied_to_interest",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "applied_to_principal",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dealership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bhph_payments",
                        to="dealer_ai.dealership",
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="dealer_ai.bhphnote",
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_at", "-created_at"],
            },
        ),
    ]
