# Generated by Django 5.0.6 on 2026-08-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_ai", "0038_m122_bhph_payment_entity"),
    ]

    operations = [
        migrations.AddField(
            model_name="bhphnote",
            name="current_bucket",
            field=models.CharField(
                choices=[
                    ("current", "Current"),
                    ("1_15", "1-15 days"),
                    ("16_30", "16-30 days"),
                    ("31_60", "31-60 days"),
                    ("61_90", "61-90 days"),
                    ("over_90", "Over 90 days"),
                    ("charge_off_candidate", "Charge-off candidate"),
                ],
                default="current",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="bhphnote",
            name="days_past_due",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
