# Generated by Django 5.0.6 on 2026-08-02 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_ai", "0039_m123_bhph_note_aging_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="BhphPromiseToPay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "promised_at",
                    models.DateTimeField(
                        help_text="When the customer said they would pay."
                    ),
                ),
                (
                    "promised_amount",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "promised_reason",
                    models.CharField(
                        choices=[
                            ("paycheck", "Paycheck"),
                            ("tax_refund", "Tax refund"),
                            ("family_help", "Family help"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("promised", "Promised"),
                            ("kept", "Kept"),
                            ("broken", "Broken"),
                        ],
                        default="promised",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actual_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciled_promises",
                        to="dealer_ai.bhphpayment",
                    ),
                ),
                (
                    "dealership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bhph_promises",
                        to="dealer_ai.dealership",
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promises",
                        to="dealer_ai.bhphnote",
                    ),
                ),
            ],
            options={
                "ordering": ["-promised_at", "-created_at"],
            },
        ),
    ]
