# Generated by Django 5.0.6 on 2026-08-02 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_ai", "0040_m124_bhph_promise_to_pay"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contacted_at",
                    models.DateTimeField(
                        help_text="Operator-supplied timestamp for the contact attempt."
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("phone", "Phone"),
                            ("letter", "Letter"),
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("in_person", "In person"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("contact_made", "Contact made"),
                            ("left_message", "Left message"),
                            ("no_answer", "No answer"),
                            ("refused_to_speak", "Refused to speak"),
                        ],
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contacted_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dealership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_contacts",
                        to="dealer_ai.dealership",
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_contacts",
                        to="dealer_ai.bhphnote",
                    ),
                ),
            ],
            options={
                "ordering": ["-contacted_at", "-created_at"],
            },
        ),
    ]
