# Generated by Django 5.0.6 on 2026-08-02 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_ai", "0041_m125_collection_contact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Repossession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordered_at",
                    models.DateTimeField(
                        help_text="When the repossession order was issued."
                    ),
                ),
                ("agent_name", models.CharField(max_length=255)),
                ("recovered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recovery_location",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ordered", "Ordered"),
                            ("recovered", "Recovered"),
                            ("re_intaked", "Re-intaked"),
                        ],
                        default="ordered",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dealership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repossessions",
                        to="dealer_ai.dealership",
                    ),
                ),
                (
                    "intake_condition_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repossession_intake",
                        to="dealer_ai.conditionreport",
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repossessions",
                        to="dealer_ai.bhphnote",
                    ),
                ),
                (
                    "ordered_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-ordered_at", "-created_at"],
            },
        ),
    ]
