# Generated by Django 5.0.6 on 2026-08-02 16:08
# Milestone 13 · Increment 1 (SESSION_129) — accounting substrate.
#
# Creates GLAccount + JournalEntry + JournalEntryLine per §5.a Option A
# / §5.c Option A / §5.e Option A + seeds the platform-default chart
# of accounts (§5.b Option A) into every existing Dealership via
# ``_seed_default_coa`` (RunPython).
#
# The seeding step imports :data:`services.accounting.DEFAULT_COA` for
# the source-of-truth tuple, but writes rows via the historical
# ``apps.get_model("dealer_ai", "GLAccount")`` — so the migration
# stays self-contained against future model changes.

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def _seed_default_coa(apps, schema_editor):
    """Seed the M13.1 default COA into every existing Dealership.

    Idempotent via ``get_or_create`` — safe to re-run against a
    partially-seeded environment. New Dealerships created after this
    migration applies are NOT auto-seeded (no ``post_save`` signal
    wiring per §0.a — explicit call defers to M14+ operator UI).
    """
    from dealer_ai.services.accounting.default_coa import DEFAULT_COA

    Dealership = apps.get_model("dealer_ai", "Dealership")
    GLAccount = apps.get_model("dealer_ai", "GLAccount")

    for dealership in Dealership.objects.all():
        for code, name, account_type in DEFAULT_COA:
            GLAccount.objects.get_or_create(
                dealership=dealership,
                code=code,
                defaults={"name": name, "account_type": account_type},
            )


def _unseed_default_coa(apps, schema_editor):
    """Reverse the seeding step (used only for full migration rewinds).

    Deletes every GLAccount whose ``code`` matches a DEFAULT_COA
    member — operator-added accounts (M14+) survive the rewind.
    """
    from dealer_ai.services.accounting.default_coa import DEFAULT_COA

    GLAccount = apps.get_model("dealer_ai", "GLAccount")
    default_codes = [code for code, _, _ in DEFAULT_COA]
    GLAccount.objects.filter(code__in=default_codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_ai", "0042_m126_repossession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GLAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=16)),
                ("name", models.CharField(max_length=255)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Equity"),
                            ("revenue", "Revenue"),
                            ("expense", "Expense"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dealership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gl_accounts",
                        to="dealer_ai.dealership",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("posted_at", models.DateTimeField()),
                ("reason", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dealership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to="dealer_ai.dealership",
                    ),
                ),
                (
                    "posted_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reverses",
                    models.ForeignKey(
                        blank=True,
                        help_text="If this entry reverses another, points at the original.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="dealer_ai.journalentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntryLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("memo", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_lines",
                        to="dealer_ai.glaccount",
                    ),
                ),
                (
                    "dealership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entry_lines",
                        to="dealer_ai.dealership",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="dealer_ai.journalentry",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="glaccount",
            constraint=models.UniqueConstraint(
                fields=("dealership", "code"),
                name="uniq_gl_account_code_per_dealership",
            ),
        ),
        migrations.RunPython(_seed_default_coa, _unseed_default_coa),
    ]
