# Generated by Django 5.0.6 on 2026-08-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_ai", "0043_m131_accounting_substrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclecost",
            name="posted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
