# Generated by Django 5.0.6 on 2026-08-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_ai", "0044_m132_vehicle_cost_posted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="bhphpayment",
            name="posted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
