# Generated by Django 5.0.6 on 2026-08-02 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_ai", "0045_m161_bhph_payment_posted_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrialBalanceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("as_of", models.DateTimeField()),
                ("total_debits", models.DecimalField(decimal_places=2, max_digits=14)),
                ("total_credits", models.DecimalField(decimal_places=2, max_digits=14)),
                ("is_balanced", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dealership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trial_balance_snapshots",
                        to="dealer_ai.dealership",
                    ),
                ),
            ],
            options={
                "ordering": ["-as_of", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrialBalanceSnapshotRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_code", models.CharField(max_length=16)),
                ("account_name", models.CharField(max_length=255)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Equity"),
                            ("revenue", "Revenue"),
                            ("expense", "Expense"),
                        ],
                        max_length=16,
                    ),
                ),
                ("debit_total", models.DecimalField(decimal_places=2, max_digits=14)),
                ("credit_total", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "natural_balance",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dealership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trial_balance_snapshot_rows",
                        to="dealer_ai.dealership",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="dealer_ai.trialbalancesnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["account_code"],
            },
        ),
        migrations.AddConstraint(
            model_name="trialbalancesnapshot",
            constraint=models.UniqueConstraint(
                fields=("dealership", "as_of"),
                name="uniq_trial_balance_snapshot_per_dealer_as_of",
            ),
        ),
        migrations.AddConstraint(
            model_name="trialbalancesnapshotrow",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "account_code"),
                name="uniq_trial_balance_snapshot_row_per_account",
            ),
        ),
    ]
