# Generated by Django 5.0.6 on 2026-08-02 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_ai", "0046_m171_trial_balance_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealership",
            name="demo_archetype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("retail_subprime", "Retail / Subprime"),
                    ("floor_planned", "Floor-planned / Recon-heavy"),
                    ("bhph", "BHPH portfolio"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="dealership",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="TesterFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tester_name", models.CharField(max_length=64)),
                ("scenario_slug", models.CharField(max_length=64)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("confusion", "Confusion"),
                            ("bug", "Bug"),
                            ("feature_request", "Feature request"),
                            ("value_statement", "Value statement"),
                            ("willingness_to_pay", "Willingness to pay"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note", models.TextField()),
                (
                    "referenced_route",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dealership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tester_feedback",
                        to="dealer_ai.dealership",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
