# Generated by Django 5.0.6 on 2026-08-02 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_ai", "0047_m181_demo_store_substrate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dealership",
            name="is_pilot",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dealership",
            name="outbound_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dealership",
            name="terminated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dealership",
            name="termination_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="PilotOnboardingChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_ready", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dealership",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pilot_onboarding_checklist",
                        to="dealer_ai.dealership",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PilotOnboardingStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_slug",
                    models.CharField(
                        choices=[
                            ("dealership_created", "Dealership created"),
                            ("profile_configured", "Profile configured"),
                            ("owner_user_added", "Owner user added"),
                            ("staff_users_added", "Staff users added"),
                            ("inventory_imported", "Inventory imported"),
                            ("capabilities_enabled", "Capabilities enabled"),
                            ("readiness_confirmed", "Readiness confirmed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("completed_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="dealer_ai.pilotonboardingchecklist",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dealership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pilot_onboarding_steps",
                        to="dealer_ai.dealership",
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PilotProspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_name", models.CharField(max_length=64)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "contact_phone",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("dealer_business_name", models.CharField(max_length=255)),
                (
                    "dealer_type",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("bhph_enabled", models.BooleanField(default=False)),
                (
                    "estimated_inventory_size",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "contact_source",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "eligibility_state",
                    models.CharField(
                        choices=[
                            ("prospect", "Prospect"),
                            ("qualified", "Qualified"),
                            ("converted", "Converted"),
                            ("declined", "Declined"),
                        ],
                        default="prospect",
                        max_length=32,
                    ),
                ),
                ("chris_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "converted_dealership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pilot_prospect_source",
                        to="dealer_ai.dealership",
                    ),
                ),
                (
                    "source_demo_dealership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pilot_prospects_from_demo",
                        to="dealer_ai.dealership",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="pilotonboardingstep",
            constraint=models.UniqueConstraint(
                fields=("checklist", "step_slug"),
                name="uniq_pilot_onboarding_step_per_checklist",
            ),
        ),
    ]
