# Generated by Django 5.0.6 on 2026-08-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_ai", "0048_m191_pilot_substrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerlead",
            name="source_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
