# Generated by Django 5.0.6 on 2026-09-01 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_ai", "0053_m227_work_order_estimate_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="conditionfinding",
            name="discovered_during_work",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="conditionfinding",
            name="discovered_on_work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="findings_discovered_during",
                to="dealer_ai.workorder",
            ),
        ),
    ]
