# Generated by Django 5.0.6 on 2026-09-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_ai", "0054_m227_condition_finding_discovered_during_work"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealeronboardingprofile",
            name="recon_authorization_mode",
            field=models.CharField(
                choices=[
                    ("per_job", "Approve every job"),
                    ("budget", "Auto-authorize under budget"),
                ],
                default="per_job",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="dealeronboardingprofile",
            name="recon_budget_bands",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="dealeronboardingprofile",
            name="recon_budget_default",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
