# Generated by Django 5.0.6 on 2026-09-01 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_ai", "0055_m228_recon_budget_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReconRateCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "work_order_category",
                    models.CharField(
                        choices=[
                            ("mechanical", "Mechanical"),
                            ("cosmetic", "Cosmetic / paint"),
                            ("body", "Body / structural"),
                            ("glass", "Glass"),
                            ("tires", "Tires"),
                            ("interior", "Interior"),
                            ("fluids", "Fluids"),
                            ("electrical", "Electrical"),
                            ("safety", "Safety"),
                            ("accessories", "Accessories / features present"),
                            ("missing", "Missing items"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("flat_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("variant", models.CharField(blank=True, default="", max_length=64)),
                ("retail_default", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dealership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recon_rate_cards",
                        to="dealer_ai.dealership",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recon rate card item",
                "verbose_name_plural": "Recon rate card items",
                "ordering": ("name", "variant"),
            },
        ),
        migrations.AddConstraint(
            model_name="reconratecard",
            constraint=models.UniqueConstraint(
                fields=("dealership", "name", "variant"),
                name="uniq_rate_card_per_store",
            ),
        ),
    ]
