# Generated by Django 5.0.6 on 2026-09-02 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_ai", "0057_m228_vehicle_recon_budget_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="conditionfinding",
            name="rate_card_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="findings",
                to="dealer_ai.reconratecard",
            ),
        ),
    ]
