# Generated by Django 5.0.6 on 2026-09-02 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer_ai", "0058_m228_condition_finding_rate_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderpart",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parts",
                to="dealer_ai.vendor",
            ),
        ),
        migrations.AlterField(
            model_name="workorderpart",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("outside_vendor", "Outside vendor / body shop"),
                    ("oem_dealer", "OEM dealer counter"),
                    ("local_parts", "Local parts store"),
                    ("online", "Online"),
                    ("salvage", "Salvage / recycled"),
                    ("in_stock", "In-house stock"),
                    ("customer_supplied", "Customer supplied"),
                    ("other", "Other"),
                ],
                default="in_stock",
                max_length=32,
            ),
        ),
    ]
